resource "auth0_connection" "github" {
  display_name         = null
  is_domain_connection = false
  metadata             = {}
  name                 = "github"
  realms               = ["github"]
  show_as_button       = null
  strategy             = "github"
  authentication {
    active = true
  }
  connected_accounts {
    active = false
  }
  options {
    access_token_url                       = null
    adfs_server                            = null
    allowed_audiences                      = []
    api_enable_groups                      = false
    api_enable_users                       = false
    app_id                                 = null
    auth_params                            = {}
    authorization_endpoint                 = null
    brute_force_protection                 = false
    client_id                              = var.github_oauth_client_id
    client_secret                          = var.github_oauth_client_secret
    community_base_url                     = null
    configuration                          = null
    consumer_key                           = null
    consumer_secret                        = null
    custom_scripts                         = {}
    debug                                  = false
    destination_url                        = null
    digest_algorithm                       = null
    disable_cache                          = false
    disable_self_service_change_password   = false
    disable_sign_out                       = false
    disable_signup                         = false
    discovery_url                          = null
    domain                                 = null
    domain_aliases                         = []
    dpop_signing_alg                       = null
    email                                  = false
    enable_script_context                  = false
    enabled_database_customization         = false
    entity_id                              = null
    fed_metadata_xml                       = null
    fields_map                             = null
    forward_request_info                   = false
    from                                   = null
    gateway_url                            = null
    global_token_revocation_jwt_iss        = null
    global_token_revocation_jwt_sub        = null
    icon_url                               = null
    id_token_session_expiry_supported      = false
    id_token_signed_response_algs          = []
    identity_api                           = null
    import_mode                            = false
    ips                                    = []
    issuer                                 = null
    jwks_uri                               = null
    key_id                                 = null
    map_user_id_to_id                      = false
    max_groups_to_retrieve                 = null
    messaging_service_sid                  = null
    metadata_url                           = null
    metadata_xml                           = null
    name                                   = null
    non_persistent_attrs                   = []
    password_policy                        = null
    ping_federate_base_url                 = null
    pkce_enabled                           = false
    precedence                             = []
    protocol_binding                       = null
    provider                               = null
    realm_fallback                         = false
    recipient_url                          = null
    request_template                       = null
    request_token_url                      = null
    requires_username                      = false
    scopes                                 = ["email", "profile", "read_org"]
    scripts                                = {}
    send_back_channel_nonce                = false
    session_key                            = null
    set_user_root_attributes               = null
    should_trust_email_verified_connection = null
    sign_in_endpoint                       = null
    sign_out_endpoint                      = null
    sign_saml_request                      = false
    signature_algorithm                    = null
    signature_method                       = null
    signing_cert                           = null
    strategy_version                       = 0
    subject                                = null
    syntax                                 = null
    team_id                                = null
    template                               = null
    tenant_domain                          = null
    token_endpoint                         = null
    token_endpoint_auth_method             = null
    token_endpoint_auth_signing_alg        = null
    token_endpoint_jwtca_aud_format        = null
    twilio_sid                             = null
    twilio_token                           = null
    type                                   = null
    upstream_params                        = null
    use_cert_auth                          = false
    use_kerberos                           = false
    use_oauth_spec_scope                   = false
    use_wsfed                              = false
    user_authorization_url                 = null
    user_id_attribute                      = null
    userinfo_endpoint                      = null
    waad_common_endpoint                   = false
    waad_protocol                          = null
  }
}

resource "auth0_connection_clients" "github" {
  connection_id   = auth0_connection.github.id
  enabled_clients = [auth0_client.copilot_credits.client_id]
}